// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PawConnect.Infrastructure;

#nullable disable

namespace PawConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PawConnect.Domain.PetModel.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<string>("HealthInfo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("health_info");

                    b.Property<double>("HeightInCm")
                        .HasColumnType("double precision")
                        .HasColumnName("height_in_cm");

                    b.Property<bool>("IsCastrated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_castrated");

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vaccinated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("VolunteerId")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_id");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_in_kg");

                    b.ComplexProperty<Dictionary<string, object>>("Breed", "PawConnect.Domain.PetModel.Pet.Breed#Breed", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("BreedId")
                                .HasColumnType("uuid")
                                .HasColumnName("breed_breed_id");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ContactNumber", "PawConnect.Domain.PetModel.Pet.ContactNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("contact_number_phone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Location", "PawConnect.Domain.PetModel.Pet.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("location_building_number");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("location_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("location_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("location_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("location_street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Species", "PawConnect.Domain.PetModel.Pet.Species#Species", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("SpeciesId")
                                .HasColumnType("uuid")
                                .HasColumnName("species_species_id");
                        });

                    b.HasKey("Id");

                    b.HasIndex("VolunteerId");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("PawConnect.Domain.SpeciesModel.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("breed");
                });

            modelBuilder.Entity("PawConnect.Domain.SpeciesModel.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("PawConnect.Domain.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExperienceInYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_in_years");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "PawConnect.Domain.Volunteer.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("email_email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PhoneNumber", "PawConnect.Domain.Volunteer.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("phone_number_phone");
                        });

                    b.HasKey("Id");

                    b.ToTable("volunteers", (string)null);
                });

            modelBuilder.Entity("PawConnect.Domain.PetModel.Pet", b =>
                {
                    b.HasOne("PawConnect.Domain.Volunteer", null)
                        .WithMany("Pets")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("PawConnect.Domain.ValueObjects.Donation", "Donation", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("pet_id");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("donation");

                            b1.WithOwner()
                                .HasForeignKey("PetId");

                            b1.OwnsMany("PawConnect.Domain.ValueObjects.DonationDetails", "DonationDetails", b2 =>
                                {
                                    b2.Property<Guid>("DonationPetId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("donation_pet_id");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("_synthesized_ordinal");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("__synthesizedOrdinal"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasMaxLength(400)
                                        .HasColumnType("character varying(400)")
                                        .HasColumnName("description");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("title");

                                    b2.HasKey("DonationPetId", "__synthesizedOrdinal");

                                    b2.ToTable("pets");

                                    b2.ToJson("DonationDetails");

                                    b2.WithOwner()
                                        .HasForeignKey("DonationPetId");
                                });

                            b1.Navigation("DonationDetails");
                        });

                    b.Navigation("Donation")
                        .IsRequired();
                });

            modelBuilder.Entity("PawConnect.Domain.SpeciesModel.Breed", b =>
                {
                    b.HasOne("PawConnect.Domain.SpeciesModel.Species", null)
                        .WithMany("Breeds")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PawConnect.Domain.Volunteer", b =>
                {
                    b.OwnsOne("PawConnect.Domain.ValueObjects.SocialNetworks", "SocialNetworks", b1 =>
                        {
                            b1.Property<Guid>("VolunteerId")
                                .HasColumnType("uuid")
                                .HasColumnName("volunteer_id");

                            b1.HasKey("VolunteerId");

                            b1.ToTable("volunteers");

                            b1.ToJson("social_networks");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerId");

                            b1.OwnsMany("PawConnect.Domain.ValueObjects.SocialNetworkDetails", "Details", b2 =>
                                {
                                    b2.Property<Guid>("SocialNetworksVolunteerId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("social_networks_volunteer_id");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("_synthesized_ordinal");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("__synthesizedOrdinal"));

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("title");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("url");

                                    b2.HasKey("SocialNetworksVolunteerId", "__synthesizedOrdinal");

                                    b2.ToTable("volunteers");

                                    b2.ToJson("Details");

                                    b2.WithOwner()
                                        .HasForeignKey("SocialNetworksVolunteerId");
                                });

                            b1.Navigation("Details");
                        });

                    b.OwnsOne("PawConnect.Domain.ValueObjects.Donation", "Donation", b1 =>
                        {
                            b1.Property<Guid>("VolunteerId")
                                .HasColumnType("uuid")
                                .HasColumnName("volunteer_id");

                            b1.HasKey("VolunteerId");

                            b1.ToTable("volunteers");

                            b1.ToJson("donation");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerId");

                            b1.OwnsMany("PawConnect.Domain.ValueObjects.DonationDetails", "DonationDetails", b2 =>
                                {
                                    b2.Property<Guid>("DonationVolunteerId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("donation_volunteer_id");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("_synthesized_ordinal");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("__synthesizedOrdinal"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasMaxLength(400)
                                        .HasColumnType("character varying(400)")
                                        .HasColumnName("description");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("title");

                                    b2.HasKey("DonationVolunteerId", "__synthesizedOrdinal");

                                    b2.ToTable("volunteers");

                                    b2.ToJson("DonationDetails");

                                    b2.WithOwner()
                                        .HasForeignKey("DonationVolunteerId");
                                });

                            b1.Navigation("DonationDetails");
                        });

                    b.Navigation("Donation")
                        .IsRequired();

                    b.Navigation("SocialNetworks")
                        .IsRequired();
                });

            modelBuilder.Entity("PawConnect.Domain.SpeciesModel.Species", b =>
                {
                    b.Navigation("Breeds");
                });

            modelBuilder.Entity("PawConnect.Domain.Volunteer", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
